### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by MiXaiLL76** [deathbeds/jyg#16]
## Description

![изображение](https://github.com/user-attachments/assets/579ecb00-fe8b-4e59-a07c-524802f0d203)

Unable to start jyg
jupyterlab 4.3.0

## Reproduce

1. `pip3 install jyg`
2. jyg run help:about

## Expected behavior

The jupyter command will be executed to open the help:about window.

## Context

- Operating System and version: Windows 11
- Browser and version: Firefox 133.0.3
- JupyterLab version: 4.3.0
- jyg version(s): 0.1.2

<details><summary>Required: installed server extensions</summary>
<pre>
Config dir: /home/sinarian/venvs/sinara/etc/jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 2.2.5 OK
    jupyter_server_proxy enabled
    - Validating jupyter_server_proxy...
      jupyter_server_proxy 4.4.0 OK
    jupyter_app_launcher enabled
    - Validating jupyter_app_launcher...
      jupyter_app_launcher 0.3.1 OK
    jupyter_resource_usage enabled
    - Validating jupyter_resource_usage...
      jupyter_resource_usage  OK
    jupyter_server_mathjax enabled
    - Validating jupyter_server_mathjax...
      jupyter_server_mathjax  OK
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
      jupyter_server_terminals 0.5.3 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 4.3.0 OK
    jupyterlab_code_formatter enabled
    - Validating jupyterlab_code_formatter...
      jupyterlab_code_formatter 3.0.2 OK
    jupyterlab_git enabled
    - Validating jupyterlab_git...
      jupyterlab_git 0.50.2 OK
    jyg enabled
    - Validating jyg...
      jyg 0.1.2 OK
    nbdime enabled
    - Validating nbdime...
      nbdime 4.0.2 OK
    notebook_shim enabled
    - Validating notebook_shim...
      notebook_shim  OK

Config dir: /usr/local/etc/jupyter
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v4.3.0
/home/sinarian/venvs/sinara/share/jupyter/labextensions
        jupyter-matplotlib v0.11.4 enabled OK
        jupyterlab-plotly v5.24.1 enabled  X
        jupyter_app_launcher v0.3.1 enabled OK (python, jupyter_app_launcher)
        jupyterlab_code_formatter v3.0.2 enabled OK (python, jupyterlab_code_formatter)
        nbdime-jupyterlab v3.0.2 enabled OK
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        jupyterlab-limit-output v2.0.0 enabled OK (python, jupyterlab_limit_output)
        @jupyterlab/git v0.50.2 enabled OK (python, jupyterlab-git)
        @jupyter-widgets/jupyterlab-manager v5.0.13 enabled OK (python, jupyterlab_widgets)
        @jupyter-server/resource-usage v0.6.0 enabled  X (python, jupyter-resource-usage)
        @jupyterhub/jupyter-server-proxy v4.4.0 enabled OK
        @deathbeds/jyg v0.1.2 enabled  X

   The following extensions may be outdated or specify dependencies that are incompatible with the current version of jupyterlab:
        jupyterlab-plotly
        @jupyter-server/resource-usage
        @deathbeds/jyg
        
   If you are a user, check if an update is available for these packages.
   If you are a developer, re-run with `--verbose` flag for more details.

Disabled extensions:
    @jupyterlab/apputils-extension:announcements
</pre>
</details>

JupyterLab server output:

```
[W 2024-12-30 09:58:52.071 ServerApp] 403 POST /jyg/commands/help:about?token= (172.17.0.2): '_xsrf' argument missing from POST
[W 2024-12-30 09:58:52.071 ServerApp] wrote error: "'_xsrf' argument missing from POST"
    Traceback (most recent call last):
      File "/home/sinarian/venvs/sinara/lib/python3.10/site-packages/tornado/web.py", line 1769, in _execute
        result = await result  # type: ignore
      File "/home/sinarian/venvs/sinara/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 751, in prepare
        await super().prepare()
      File "/home/sinarian/venvs/sinara/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 633, in prepare
        self.check_xsrf_cookie()
      File "/home/sinarian/venvs/sinara/lib/python3.10/site-packages/jupyter_server/base/handlers.py", line 537, in check_xsrf_cookie
        return super().check_xsrf_cookie()
      File "/home/sinarian/venvs/sinara/lib/python3.10/site-packages/tornado/web.py", line 1605, in check_xsrf_cookie
        raise HTTPError(403, "'_xsrf' argument missing from POST")
    tornado.web.HTTPError: HTTP 403: Forbidden ('_xsrf' argument missing from POST)
[W 2024-12-30 09:58:52.071 ServerApp] 403 POST /jyg/commands/help:about?token=[secret] (2409a06b723148cdb4733b73ac5c54ef@172.17.0.2) 1.08ms referer=None
```

Jupyter Start CMD:
```bash
start-notebook.sh --ip=0.0.0.0 --port=8888 --NotebookApp.default_url=/lab --ServerApp.allow_password_change=False --NotebookApp.token= --NotebookApp.password=
```

**Comment by jjsantos01** [comment]
I got exactly the same error. 
Running:
- Windows 11 
- JupyterLab version: 4.3.6
- jyg version(s): 0.1.2
